manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: kuolemax
      url-base: https://github.com/kuolemax
  projects:
    - name: zmk
      # remote: zmkfirmware
      # revision: main
      remote: kuolemax
      revision: encoder-fix
      import: app/west.yml
  self:
    path: config
